# Generated by Django 3.2.5 on 2022-07-03 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('client_name', models.CharField(max_length=1000, verbose_name='Client name')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('login', models.CharField(max_length=25, verbose_name='Login')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('born_date', models.DateField(blank=True, default=None, null=True, verbose_name='Born Date')),
                ('last_connection', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date of the Last Connection')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('years_seniority', models.IntegerField(default=0, verbose_name='Seniority')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date of Birthday')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='route_app_3.userprofile')),
                ('specialization', models.CharField(max_length=50, verbose_name='Specialization')),
            ],
            bases=('route_app_3.userprofile',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('time_elapsed', models.IntegerField(blank=True, default=None, null=True, verbose_name='Elapsed Time')),
                ('importance', models.IntegerField(verbose_name='Importance')),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route_app_3.userprofile', verbose_name='User')),
                ('project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='route_app_3.project', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='route_app_3.userprofile')),
                ('supervisor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route_app_3.supervisor', verbose_name='Supervisor')),
            ],
            bases=('route_app_3.userprofile',),
        ),
    ]
